I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter1.rpy", line 12, in script call
    call free_day
  File "game/script.rpy", line 71, in script
    
  File "game/script.rpy", line 71, in <module>
    
NameError: name 'character_stat1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter1.rpy", line 12, in script call
    call free_day
  File "game/script.rpy", line 71, in script
    
  File "C:\Users\Pheon\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Pheon\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 71, in <module>
    
NameError: name 'character_stat1' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Call of the Truth 1.0
Thu May 21 21:05:21 2020
